(() => {
  "use strict";

  // Card metadata only. Question content is always read from content/*.json.
  const state = {
    screen:"pick", job:null, skills:{}, revised:[], plan:[], cursor:0, confidence:60,
    lifelines:{ repeat:2, thinkAloud:3, dontKnow:1 }, eliminated:[], timeLeft:45,
    history:[], timer:null, speakTimer:null, gateTimer:null, speaking:false, locked:false, jobs:[],
    currentLifelines:[], questionStartConfidence:60, orderItems:[], orderChosen:null,
    dragId:null, briefingLeft:30, lastError:"",
    catalogue:[], customLevel:"mid", customSkills:[], customTitle:""
  };

  // Custom mode: the candidate writes the posting themselves.
  const CUSTOM_SKILLS = 5, REVISE_MAX = 3;
  const LEVELS = [
    { id:"junior", name:"Junior", note:"0-2 yrs" },
    { id:"mid",    name:"Mid",    note:"2-5 yrs" },
    { id:"senior", name:"Senior", note:"5+ yrs" }
  ];
  const CUSTOM_ROUNDS = [
    { id:"hr",        name:"HR Screen",        interviewer:{ name:"Nadia",  role:"Talent Partner"     }, want:5 },
    { id:"technical", name:"Technical Screen", interviewer:{ name:"Tobias", role:"Senior Engineer"    }, want:7 },
    { id:"deepdive",  name:"Deep Dive",        interviewer:{ name:"Priya",  role:"Staff Engineer"     }, want:6 },
    { id:"ask",       name:"The Ask",          interviewer:{ name:"Daniel", role:"Engineering Manager"}, want:5 }
  ];

  const el = id => document.getElementById(id);
  const screens = [...document.querySelectorAll("[data-screen]")];
  const clamp = (n,min,max) => Math.min(max,Math.max(min,n));
  const escapeHtml = value => String(value).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[c]);
  const signed = n => n > 0 ? `+${n}` : String(n);
  const initials = name => name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();

  function setScreen(name) {
    if (state.timer) { clearInterval(state.timer); state.timer=null; }
    if (state.speakTimer) { clearTimeout(state.speakTimer); state.speakTimer=null; }
    if (state.gateTimer) { clearTimeout(state.gateTimer); state.gateTimer=null; }
    state.speaking=false; el("round-gate").hidden=true;
    state.screen=name;
    screens.forEach(node=>{ node.hidden=node.dataset.screen!==name; });
    scrollTo({top:0,behavior:"smooth"});
  }

  function loadJson(path) {
    const bundle=window.CTI_CONTENT?.files;
    if(!bundle) throw new Error("content.js did not load. It sits next to index.html and is generated by validate.py.");
    const data=bundle[path];
    if(!data) throw new Error(`${path} is missing from content.js — run python3 validate.py to rebuild it.`);
    return data;
  }

  function shuffle(items) {
    const result=[...items], random=new Uint32Array(result.length);
    if(crypto?.getRandomValues) crypto.getRandomValues(random);
    for(let i=result.length-1;i>0;i--){
      const unit=crypto?.getRandomValues ? random[i]/4294967296 : Math.random();
      const j=Math.floor(unit*(i+1)); [result[i],result[j]]=[result[j],result[i]];
    }
    return result;
  }

  function validateQuestion(q,source) {
    if(!q?.id||!q.type||!q.stage||!Array.isArray(q.levels)||!q.prompt||!q.explanation) throw new Error(`${source}: malformed question`);
    if(["mcq","red-flag"].includes(q.type)){
      if(!Array.isArray(q.options)||q.options.length!==4) throw new Error(`${source}/${q.id}: expected exactly 4 options`);
      if(!Number.isInteger(q.correct)||q.correct<0||q.correct>3) throw new Error(`${source}/${q.id}: invalid correct option`);
      if(!Number.isInteger(q.eliminate)||q.eliminate<0||q.eliminate>3) throw new Error(`${source}/${q.id}: invalid eliminate option`);
    }
    if(q.type==="order"){
      const a=(q.items||[]).map(x=>x.id).sort(), b=[...(q.correctOrder||[])].sort();
      if(a.length!==b.length||a.some((id,i)=>id!==b[i])) throw new Error(`${source}/${q.id}: correctOrder does not match items`);
    }
    if(q.type==="open"&&(!q.modelAnswer||!Array.isArray(q.keyPoints))) throw new Error(`${source}/${q.id}: incomplete open answer`);
  }

  function validateBanks(job,skills) {
    const required=new Set([...job.topics.flatMap(t=>t.skills),"behavioral"]);
    required.forEach(skill=>{
      if(!skills[skill]?.questions) throw new Error(`Missing skill bank: ${skill}.json`);
      skills[skill].questions.forEach(q=>validateQuestion(q,`skills/${skill}.json`));
    });
    (job.extra||[]).forEach(q=>validateQuestion(q,`${job.slug}/extra`));
  }

  function validateLoaded(job,skills) {
    if(job.topics?.length!==6||job.rounds?.length!==4) throw new Error(`${job.slug}: expected 6 topics and 4 rounds`);
    validateBanks(job,skills);
  }

  function assemblePlan(job,skills) {
    const candidates=[];
    Object.entries(skills).forEach(([skill,bank])=>{
      const topic=skill==="behavioral" ? null : job.topics.find(t=>t.skills.includes(skill));
      bank.questions.forEach(question=>candidates.push({question,skill,topic:topic?.id||null}));
    });
    (job.extra||[]).forEach(question=>candidates.push({question,skill:"extra",topic:null}));
    const used=new Set(), plan=[];
    job.rounds.forEach((round,index)=>{
      const pool=candidates.filter(({question:q})=>q.stage===round.id&&q.levels.includes(job.level)&&(!q.platform||job.platform==="any"||q.platform===job.platform)&&!used.has(q.id));
      shuffle(pool).slice(0,round.count).forEach(item=>{
        used.add(item.question.id); plan.push({...item,round:{...round,index}});
      });
    });
    return plan;
  }

  function logPlan() {
    console.group(`Crack the Interview · ${state.job.slug}`);
    console.table(state.plan.map((x,i)=>({n:i+1,round:x.round.id,id:x.question.id,type:x.question.type,skill:x.skill,topic:x.topic||"—"})));
    console.groupEnd();
  }

  async function loadJobs() {
    try{
      const data=await loadJson("content/index.json");
      if(!Array.isArray(data.jobs)) throw new Error("content/index.json has no jobs array");
      state.jobs=data.jobs; renderJobs();
    }catch(error){ showError(error); }
  }

  function renderJobs() {
    el("pick-status").textContent=`${state.jobs.length} roles open · every interview is shuffled fresh · or write the posting yourself`;
    const build=`<button class="job-card build" data-custom><span class="job-top"><span><span class="job-kicker">your call</span><h2>Customize your interview</h2></span><span class="arrow">+</span></span><span class="tags"><span class="tag">Pick 5 skills</span><span class="tag">Pick your level</span></span><span class="job-foot"><span>Any combination</span><span>Assembled on the spot</span></span></button>`;
    el("job-grid").innerHTML=build+state.jobs.map(job=>`<button class="job-card" data-job="${escapeHtml(job.slug)}"><span class="job-top"><span><span class="job-kicker">${escapeHtml(job.level)} role</span><h2>${escapeHtml(job.title)}</h2></span><span class="arrow">↗</span></span><span class="tags">${job.stack.map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join("")}</span><span class="job-foot"><span>${job.questionCount} questions</span><span>Difficulty <span class="dots">${Array.from({length:5},(_,i)=>`<span class="dot ${i<job.difficulty?"on":""}"></span>`).join("")}</span></span></span></button>`).join("");
  }


  // ---------------------------------------------------------------- custom mode
  function skillCatalogue() {
    const files=window.CTI_CONTENT?.files||{};
    return Object.keys(files).filter(path=>path.startsWith("content/skills/")).map(path=>files[path])
      .filter(bank=>bank.skill!=="behavioral")
      .map(bank=>({id:bank.skill,label:bank.label,bank}))
      .sort((a,b)=>a.label.localeCompare(b.label));
  }
  const bankFor = id => loadJson(`content/skills/${id}.json`);
  const askable = (bank,level,stage) => bank.questions.filter(q=>q.levels.includes(level)&&(!stage||q.stage===stage)).length;

  function customRounds(ids,level) {
    const banks=[...ids,"behavioral"].map(bankFor);
    return CUSTOM_ROUNDS.map(round=>{
      const have=banks.reduce((total,bank)=>total+askable(bank,level,round.id),0);
      return {id:round.id,name:round.name,interviewer:round.interviewer,count:Math.min(round.want,have)};
    }).filter(round=>round.count>0);
  }

  function buildCustomJob() {
    const level=state.customLevel, ids=state.customSkills;
    const skills=Object.fromEntries([...ids,"behavioral"].map(id=>[id,bankFor(id)]));
    const topics=ids.map(id=>({id,label:skills[id].label,skills:[id]}));
    const rounds=customRounds(ids,level);
    const levelName=LEVELS.find(l=>l.id===level).name.toLowerCase();
    const job={
      slug:"custom", custom:true, level, platform:"any",
      title:state.customTitle.trim()||`Your own interview · ${levelName} level`,
      stack:topics.map(t=>t.label),
      briefing:{
        summary:`No company behind this one — you wrote the posting. Five skills at ${levelName} level, four rounds, and a panel that takes your list at face value. Everything you put on it is fair game, and the behavioural questions come along regardless: nobody has ever skipped the HR screen. Revise three of your five and go.`,
        requirements:[...topics.map(t=>`${t.label} — ${askable(skills[t.id],level)} questions in the bank at this level`),
                      "Motivation, teamwork and disagreement — always in play, never revisable"]
      },
      topics, rounds, extra:[]
    };
    return {job,skills};
  }

  function startCustom() {
    if(state.customSkills.length!==CUSTOM_SKILLS) return;
    setScreen("loading");
    try{
      const {job,skills}=buildCustomJob();
      validateBanks(job,skills);
      if(!job.rounds.length) throw new Error("Those five skills have no questions at this level. Pick different skills, or change the level.");
      state.job=job; state.skills=skills; state.plan=assemblePlan(job,skills);
      if(!state.plan.length) throw new Error("Nothing in those banks matched that level.");
      logPlan(); startBriefing();
    }catch(error){ showError(error); }
  }

  function showCustom() {
    try{
      if(!state.catalogue.length) state.catalogue=skillCatalogue();
      setScreen("custom"); renderCustom();
    }catch(error){ showError(error); }
  }

  function renderCustom() {
    const level=state.customLevel;
    el("level-seg").innerHTML=LEVELS.map(l=>`<button class="${l.id===level?"on":""}" data-level="${l.id}">${l.name}<small>${l.note}</small></button>`).join("");
    const full=state.customSkills.length>=CUSTOM_SKILLS;
    el("skill-grid").innerHTML=state.catalogue.map(skill=>{
      const have=askable(skill.bank,level), on=state.customSkills.includes(skill.id);
      return `<button class="skill-chip ${on?"selected":""}" data-skill="${escapeHtml(skill.id)}" ${!have||(full&&!on)?"disabled":""}><span>${escapeHtml(skill.label)}</span><span class="skill-count">${have}</span></button>`;
    }).join("");
    el("skill-status").textContent=`Skills · ${state.customSkills.length} of ${CUSTOM_SKILLS}`;
    el("custom-hint").textContent=full ? "That is your five, and they count as your revision — the first question comes straight away. Deselect one to swap it out."
      : `The number on each skill is how many questions it can ask a ${LEVELS.find(l=>l.id===level).name.toLowerCase()} candidate. Greyed-out skills have none at this level.`;
    renderPlanPreview();
    el("custom-start").disabled=!full;
  }

  function renderPlanPreview() {
    if(!state.customSkills.length){ el("plan-preview").innerHTML=""; return; }
    const rounds=customRounds(state.customSkills,state.customLevel);
    const total=rounds.reduce((sum,round)=>sum+round.count,0);
    const pills=[`<span class="plan-pill lead">${total} questions</span>`,`<span class="plan-pill lead">${rounds.length} of 4 rounds</span>`,
                 ...rounds.map(round=>`<span class="plan-pill">${escapeHtml(round.name)} ${round.count}</span>`)];
    if(state.customSkills.length===CUSTOM_SKILLS&&total<14) pills.push(`<span class="plan-pill warn">thin pool · replays will repeat</span>`);
    el("plan-preview").innerHTML=pills.join("");
  }

  function setCustomLevel(level) {
    state.customLevel=level;
    state.customSkills=state.customSkills.filter(id=>askable(bankFor(id),level));
    renderCustom();
  }

  function toggleSkill(id) {
    if(state.customSkills.includes(id)) state.customSkills=state.customSkills.filter(x=>x!==id);
    else if(state.customSkills.length<CUSTOM_SKILLS) state.customSkills.push(id);
    renderCustom();
  }

  async function startJob(slug) {
    setScreen("loading");
    try{
      const job=await loadJson(`content/job-titles/${slug}.json`);
      const ids=[...new Set([...job.topics.flatMap(t=>t.skills),"behavioral"])];
      const pairs=await Promise.all(ids.map(async id=>[id,await loadJson(`content/skills/${id}.json`)]));
      const skills=Object.fromEntries(pairs); validateLoaded(job,skills);
      state.job=job; state.skills=skills; state.plan=assemblePlan(job,skills); logPlan(); startBriefing();
    }catch(error){ showError(error); }
  }

  function resetRun() {
    Object.assign(state,{revised:[],cursor:0,confidence:60,lifelines:{repeat:2,thinkAloud:3,dontKnow:1},eliminated:[],history:[],locked:false,currentLifelines:[],briefingLeft:30});
  }

  function startBriefing() {
    resetRun();
    if(state.job.custom) return skipBriefing();
    setScreen("briefing");
    el("brief-title").textContent=state.job.title; el("brief-summary").textContent=state.job.briefing.summary;
    el("requirements").innerHTML=state.job.briefing.requirements.map(x=>`<li>${escapeHtml(x)}</li>`).join("");
    renderTopics(); renderBriefClock();
    state.timer=setInterval(()=>{ state.briefingLeft=Math.max(0,state.briefingLeft-1); renderBriefClock(); if(!state.briefingLeft) beginInterview(); },1000);
  }

  const reviseTarget = () => Math.min(REVISE_MAX,state.job.topics.length);

  // You already chose five skills on the builder. Choosing three of them again is
  // the same decision twice, so a custom run counts all five as revised and opens
  // on the first question.
  function skipBriefing() {
    state.revised=state.job.topics.map(t=>t.id);
    setScreen("interview"); startInterviewTimer(); renderQuestion();
  }

  function renderTopics() {
    const target=reviseTarget();
    el("revise-instruction").textContent=`Pick exactly ${target} of your ${state.job.topics.length} topics to revise`;
    el("topic-grid").innerHTML=state.job.topics.map(t=>`<button class="topic-chip ${state.revised.includes(t.id)?"selected":""}" data-topic="${t.id}" ${state.revised.length===target&&!state.revised.includes(t.id)?"disabled":""}>${escapeHtml(t.label)}</button>`).join("");
    el("selection-copy").textContent=`${state.revised.length} of ${target} selected${state.revised.length===0?" · going in cold is legal":""}`;
    el("start-interview").disabled=state.revised.length!==target;
  }

  function toggleTopic(id) {
    if(state.revised.includes(id)) state.revised=state.revised.filter(x=>x!==id);
    else if(state.revised.length<reviseTarget()) state.revised.push(id);
    renderTopics();
  }
  function renderBriefClock(){ el("brief-clock").textContent=`0:${String(state.briefingLeft).padStart(2,"0")}`; }

  function beginInterview() {
    if(state.screen!=="briefing") return;
    setScreen("interview"); startInterviewTimer(); renderQuestion();
  }
  function startInterviewTimer(){
    state.timer=setInterval(()=>{
      if(state.screen!=="interview"||state.locked||state.speaking) return;
      state.timeLeft=Math.max(0,state.timeLeft-1); renderClock(); if(state.timeLeft===0) finalizeAnswer({timedOut:true});
    },1000);
  }

  const current=()=>state.plan[state.cursor];
  const topicLabel=id=>state.job.topics.find(t=>t.id===id)?.label||null;

  const QBODY=["question-number","prompt","subject","question-instruction","say-cue","options","order-list","open-area","lifelines","question-actions"];

  function renderQuestion() {
    const item=current(); if(!item) return showVerdict(false);
    const prev=state.plan[state.cursor-1];
    if(prev && prev.round.id===item.round.id) return paintQuestion();
    const n=state.job.rounds.findIndex(r=>r.id===item.round.id);
    state.speaking=true;
    el("gate-round").textContent=`Round ${n+1} of ${state.job.rounds.length}`;
    el("gate-name").textContent=item.round.name;
    el("gate-who").textContent=`${item.round.interviewer.name} · ${item.round.interviewer.role} has joined the call`;
    el("round-gate").hidden=false;
    state.gateTimer=setTimeout(()=>{ el("round-gate").hidden=true; paintQuestion(); },1700);
  }

  function speakQuestion() {
    state.speaking=true;
    el("them-tile").classList.remove("react-good","react-bad");
    el("them-tile").classList.add("speaking");
    el("tile-note").hidden=true; el("speaking-dots").hidden=false;
    el("you-status").textContent="listening";
    QBODY.forEach(id=>{ el(id).classList.add("q-hidden"); el(id).classList.remove("q-shown"); });
    state.speakTimer=setTimeout(()=>{
      state.speaking=false;
      el("them-tile").classList.remove("speaking"); el("speaking-dots").hidden=true;
      el("you-status").textContent="your turn";
      QBODY.forEach(id=>{ el(id).classList.remove("q-hidden"); el(id).classList.add("q-shown"); });
    },850);
  }

  function showDelta(n) {
    if(!n) return;
    const node=el("delta-float");
    node.hidden=false; node.textContent=signed(n);
    node.className="delta-float "+(n>0?"up":"down");
    node.style.animation="none"; void node.offsetWidth; node.style.animation="";
  }

  function paintQuestion() {
    const item=current(); if(!item) return showVerdict(false);
    Object.assign(state,{locked:false,eliminated:[],currentLifelines:[],questionStartConfidence:state.confidence,orderChosen:null});
    state.timeLeft=item.question.type==="open"?90:45;
    state.orderItems=item.question.type==="order"?shuffle(item.question.items):[];
    const inRound=state.plan.slice(0,state.cursor+1).filter(x=>x.round.id===item.round.id).length;
    const roundTotal=state.plan.filter(x=>x.round.id===item.round.id).length;
    el("round-label").innerHTML=`Round ${item.round.index+1} of ${state.job.rounds.length}<strong>${escapeHtml(item.round.name)}</strong>`;
    el("progress-label").innerHTML=`Question<strong>${state.cursor+1} of ${state.plan.length}</strong>`;
    el("question-number").textContent=`Question ${inRound} / ${roundTotal}`; el("question-type").textContent=item.question.type;
    el("interviewer-name").textContent=item.round.interviewer.name; el("interviewer-role").textContent=item.round.interviewer.role; el("avatar").textContent=initials(item.round.interviewer.name); el("prompt").textContent=item.question.prompt;
    ["feedback","next-row","question-instruction","order-list","open-area","lifeline-used"].forEach(id=>el(id).hidden=true);
    el("subject").innerHTML=""; el("options").innerHTML=""; el("question-actions").innerHTML=""; el("open-area").innerHTML="";
    if(item.question.type==="red-flag") renderSubject(item.question.subject);
    if(["mcq","red-flag"].includes(item.question.type)) renderOptions();
    if(item.question.type==="order") renderOrder();
    if(item.question.type==="open") renderOpen();
    el("say-cue").hidden=!["mcq","red-flag"].includes(item.question.type);
    el("delta-float").hidden=true;
    renderLifelines(); renderConfidence(); renderClock(); speakQuestion();
  }

  function renderSubject(subject) {
    if(subject.kind==="code") el("subject").innerHTML=`<div class="subject"><pre class="subject-code"><code>${escapeHtml(subject.content)}</code></pre></div>`;
    else el("subject").innerHTML=`<div class="subject"><blockquote class="subject-quote">“${escapeHtml(subject.content)}”</blockquote></div>`;
  }
  function renderOptions() {
    el("options").innerHTML=current().question.options.map((text,i)=>`<button class="option ${state.eliminated.includes(i)?"eliminated":""}" data-option="${i}"><span class="option-key">${String.fromCharCode(65+i)}</span><span class="option-text">${escapeHtml(text)}</span></button>`).join("");
  }
  function renderOrder() {
    el("question-instruction").hidden=false; el("question-instruction").textContent=`${current().question.instruction} Drag, or tap two rows to swap them.`;
    el("order-list").hidden=false;
    el("order-list").innerHTML=state.orderItems.map((x,i)=>`<button class="order-item ${state.orderChosen===x.id?"chosen":""}" draggable="true" data-order="${x.id}"><span class="order-pos">${i+1}</span><span>${escapeHtml(x.text)}</span><span class="order-grip">⠿</span></button>`).join("");
    el("question-actions").innerHTML=`<button class="action primary" data-submit-order>Lock this order</button>`;
  }
  function renderOpen() {
    el("open-area").hidden=false; el("open-area").innerHTML=`<textarea class="open-answer" id="open-response" placeholder="Talk it through here, or answer aloud…"></textarea>`;
    el("question-actions").innerHTML=`<button class="action primary" data-reveal-open>Ready — show the model answer</button>`;
  }

  function revealOpen() {
    if(state.locked) return; state.locked=true; renderLifelines();
    const q=current().question;
    el("open-area").innerHTML=`<div class="model-answer"><h3>Model answer</h3><p>${escapeHtml(q.modelAnswer)}</p><ul class="key-points">${q.keyPoints.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div>`;
    el("question-actions").innerHTML=`<div class="self-score"><button class="action good" data-self="8">I said all of that · +8</button><button class="action warn" data-self="3">I got the gist · +3</button><button class="action bad" data-self="-10">No idea · −10</button></div>`;
  }

  function optionAnswer(index) {
    if(state.locked) return; finalizeAnswer({correct:index===current().question.correct,selected:index});
  }
  function submitOrder() {
    if(state.locked) return;
    const correct=state.orderItems.every((x,i)=>x.id===current().question.correctOrder[i]); finalizeAnswer({correct});
  }
  function selfScore(delta) { if(!state.locked||state.history.some(h=>h.questionId===current().question.id)) return; finalizeAnswer({selfDelta:delta}); }

  function answerDelta({correct,timedOut,selfDelta,skipped}) {
    if(arguments[0].lifelineDrain) return 0;
    if(Number.isFinite(selfDelta)) return selfDelta;
    if(skipped) return -5;
    if(timedOut) return -15;
    if(correct){ if(current().topic&&state.revised.includes(current().topic)) return 12; return state.timeLeft<10?5:8; }
    if(current().topic&&!state.revised.includes(current().topic)) return -24;
    if(current().question.type==="red-flag") return -18;
    return -12;
  }

  function finalizeAnswer(result) {
    if(state.history.some(h=>h.questionId===current().question.id)) return;
    state.locked=true; const item=current(), delta=answerDelta(result); state.confidence=clamp(state.confidence+delta,0,100);
    const correct=result.skipped||result.lifelineDrain?null:(result.timedOut?false:(Number.isFinite(result.selfDelta)?result.selfDelta>0:result.correct));
    state.history.push({questionId:item.question.id,prompt:item.question.prompt,topic:item.topic,topicLabel:topicLabel(item.topic),skill:item.skill,round:item.round.id,roundName:item.round.name,correct,delta:state.confidence-state.questionStartConfidence,answerDelta:delta,lifeline:[...state.currentLifelines],timedOut:!!result.timedOut,confidenceAfter:state.confidence,type:item.question.type});
    if(["mcq","red-flag"].includes(item.question.type)) [...el("options").querySelectorAll(".option")].forEach((button,i)=>{button.disabled=true;if(i===item.question.correct)button.classList.add("correct");if(i===result.selected&&!result.correct)button.classList.add("wrong");});
    if(item.question.type==="order") [...el("order-list").children].forEach(x=>x.disabled=true);
    if(item.question.type==="open"&&result.timedOut){ revealModelAfterTimeout(); }
    el("question-actions").innerHTML=""; el("feedback-title").textContent=result.lifelineDrain?"Confidence drained":result.skipped?`Handled honestly · ${signed(delta)} confidence`:result.timedOut?`Time ran out · ${signed(delta)} confidence`:correct?`That landed · ${signed(delta)} confidence`:`That hurt · ${signed(delta)} confidence`;
    const tile=el("them-tile"); tile.classList.remove("react-good","react-bad","speaking"); void tile.offsetWidth;
    if(correct===true){ tile.classList.add("react-good"); el("tile-note").hidden=true; }
    else if(correct===false){ tile.classList.add("react-bad"); el("tile-note").hidden=false; }
    el("you-status").textContent="answered"; showDelta(delta);
    el("explanation").textContent=item.question.explanation; el("feedback").hidden=false; renderConfidence(); renderClock(); renderLifelines();
    if(state.confidence===0) showVerdict(true); else el("next-row").hidden=false;
  }

  function revealModelAfterTimeout(){ const q=current().question; el("open-area").hidden=false; el("open-area").innerHTML=`<div class="model-answer"><h3>Model answer</h3><p>${escapeHtml(q.modelAnswer)}</p><ul class="key-points">${q.keyPoints.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul></div>`; }

  function useLifeline(kind) {
    if(state.locked||state.lifelines[kind]<=0) return;
    const q=current().question;
    if(kind==="thinkAloud"&&!['mcq','red-flag'].includes(q.type)) return;
    state.lifelines[kind]-=1; state.currentLifelines.push(kind);
    const cost=kind==="repeat"?-3:kind==="thinkAloud"?-5:0; state.confidence=clamp(state.confidence+cost,0,100);
    if(kind==="repeat") state.timeLeft+=20;
    if(kind==="thinkAloud"){ state.eliminated.push(q.eliminate); renderOptions(); }
    el("lifeline-used").hidden=false; el("lifeline-used").textContent=kind==="repeat"?"The interviewer repeats it. You bought 20 seconds.":kind==="thinkAloud"?"Talking it through removes one weak option.":"You explain how you would find the answer instead of bluffing.";
    renderConfidence(); renderClock(); renderLifelines();
    if(state.confidence===0){ finalizeAnswer({lifelineDrain:true}); return; }
    if(kind==="dontKnow") finalizeAnswer({skipped:true});
  }

  function renderLifelines() {
    document.querySelectorAll("[data-charge]").forEach(node=>{node.textContent=state.lifelines[node.dataset.charge]});
    document.querySelectorAll("[data-lifeline]").forEach(button=>{
      const kind=button.dataset.lifeline, incompatible=kind==="thinkAloud"&&(!['mcq','red-flag'].includes(current()?.question.type)||state.currentLifelines.includes("thinkAloud"));
      button.disabled=state.locked||state.lifelines[kind]<=0||incompatible;
    });
  }

  function selectOrder(id) {
    if(state.locked)return;
    if(!state.orderChosen){state.orderChosen=id;renderOrder();return;}
    if(state.orderChosen===id){state.orderChosen=null;renderOrder();return;}
    const a=state.orderItems.findIndex(x=>x.id===state.orderChosen),b=state.orderItems.findIndex(x=>x.id===id); [state.orderItems[a],state.orderItems[b]]=[state.orderItems[b],state.orderItems[a]]; state.orderChosen=null;renderOrder();
  }
  function dropOrder(targetId){const from=state.orderItems.findIndex(x=>x.id===state.dragId),to=state.orderItems.findIndex(x=>x.id===targetId);if(from<0||to<0)return;const [moved]=state.orderItems.splice(from,1);state.orderItems.splice(to,0,moved);state.dragId=null;renderOrder();}

  function nextQuestion(){if(!state.locked)return;state.cursor++;if(state.cursor>=state.plan.length)showVerdict(false);else renderQuestion();}
  function renderConfidence(){
    const c=state.confidence, ring=el("conf-ring");
    const colour=c<20?"#fb7185":c<40?"#f59e0b":c<65?"#38bdf8":c<85?"#818cf8":"#34d399";
    const mood=c===0?"gone":c<20?"checked out":c<40?"losing them":c<65?"on the fence":c<85?"convinced":"sold";
    el("confidence-value").textContent=`${c}%`;
    ring.style.setProperty("--p",c); ring.style.setProperty("--c",colour);
    el("conf-mood").textContent=mood;
  }
  function renderClock(){el("clock").textContent=`${Math.floor(state.timeLeft/60)}:${String(state.timeLeft%60).padStart(2,"0")}`;el("clock").classList.toggle("urgent",state.timeLeft>0&&state.timeLeft<10&&!state.locked);}

  function verdictFor(score,drained){if(drained||score===0)return{title:"Rejected on the spot",copy:"The room lost confidence before the interview was over.",mark:"×"};if(score<=39)return{title:"Ghosted",copy:"No email ever comes.",mark:"…"};if(score<=64)return{title:"Waitlisted",copy:"They went with someone more senior.",mark:"◌"};if(score<=84)return{title:"Offer",copy:"You made the case. The recruiter is calling with numbers.",mark:"✓"};return{title:"Offer, and they moved fast",copy:"The paperwork is already moving.",mark:"⚡"};}
  function showVerdict(drained){setScreen("verdict");const v=verdictFor(state.confidence,drained);el("verdict-title").textContent=v.title;el("verdict-copy").textContent=v.copy;el("verdict-mark").textContent=v.mark;el("final-confidence").textContent=`${state.confidence}%`;renderDebrief();}

  function renderDebrief() {
    const histories=state.history, points=[60,...histories.map(h=>h.confidenceAfter)], width=620,height=150,pad=24;
    const xy=points.map((score,i)=>`${pad+(i/Math.max(1,points.length-1))*(width-pad*2)},${height-pad-(score/100)*(height-pad*2)}`).join(" ");
    const roundMarks=state.job.rounds.map(round=>{
      const first=histories.findIndex(h=>h.round===round.id); if(first<0)return "";
      const x=pad+((first+1)/Math.max(1,points.length-1))*(width-pad*2);
      return `<line x1="${x}" y1="${pad}" x2="${x}" y2="${height-pad}" stroke="#263751" stroke-dasharray="3 4"/><text x="${x+4}" y="${pad+10}" class="chart-label">${escapeHtml(round.name)}</text>`;
    }).join("");
    const topicStats={}; histories.filter(h=>h.topic).forEach(h=>{topicStats[h.topic]??={label:h.topicLabel,wrong:[],total:0};topicStats[h.topic].total++;if(h.correct===false)topicStats[h.topic].wrong.push(h.prompt);});
    const weakest=Object.values(topicStats).sort((a,b)=>(b.wrong.length/b.total)-(a.wrong.length/a.total))[0];
    const lifeNames={repeat:"Repeat",thinkAloud:"Think out loud",dontKnow:"Honest skip"}, life=[];
    Object.keys(lifeNames).forEach(kind=>{const used=histories.filter(h=>h.lifeline.includes(kind));if(used.length)life.push(`${lifeNames[kind]}: ${used.length} used · ${used.filter(h=>h.correct===true||kind==="dontKnow").length} paid off`);});
    const revised=state.job.topics.filter(t=>state.revised.includes(t.id));
    const revisionTitle=state.job.custom?"What you asked to be asked":"Revision vs. reality";
    const revisionHtml=revised.length?revised.map(t=>`<li>${escapeHtml(t.label)} — ${histories.filter(h=>h.topic===t.id).length} asked</li>`).join(""):"<li>You went in without revising any topic.</li>";
    el("debrief").innerHTML=`<div class="debrief-grid"><section class="debrief-card wide"><h2>Confidence across all four rounds</h2><svg class="confidence-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Confidence history"><line x1="${pad}" y1="${height-pad}" x2="${width-pad}" y2="${height-pad}" stroke="#263751"/><line x1="${pad}" y1="${pad}" x2="${pad}" y2="${height-pad}" stroke="#263751"/>${roundMarks}<polyline points="${xy}" fill="none" stroke="#818cf8" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><text x="3" y="${pad+3}" class="chart-label">100</text><text x="8" y="${height-pad+3}" class="chart-label">0</text></svg></section><section class="debrief-card"><h2>Weakest topic</h2>${weakest?`<p><strong>${escapeHtml(weakest.label)}</strong> · ${weakest.wrong.length} wrong of ${weakest.total}</p>${weakest.wrong.map(q=>`<p>• ${escapeHtml(q)}</p>`).join("")}`:"<p>No topic-specific misses to report.</p>"}</section><section class="debrief-card"><h2>Lifelines</h2>${life.length?`<ul>${life.map(x=>`<li>${x}</li>`).join("")}</ul>`:"<p>You used no lifelines.</p>"}</section><section class="debrief-card wide"><h2>${escapeHtml(revisionTitle)}</h2><ul>${revisionHtml}</ul></section></div>`;
  }

  function replay(){state.plan=assemblePlan(state.job,state.skills);logPlan();startBriefing();}
  function showPick(){state.job=null;state.skills={};state.plan=[];setScreen("pick");if(!state.jobs.length)loadJobs();}
  function showError(error){state.lastError=error?.message||String(error);el("error-detail").textContent=state.lastError;setScreen("error");}

  el("job-grid").addEventListener("click",e=>{
    if(e.target.closest("[data-custom]")) return showCustom();
    const b=e.target.closest("[data-job]");if(b)startJob(b.dataset.job);
  });
  el("level-seg").addEventListener("click",e=>{const b=e.target.closest("[data-level]");if(b)setCustomLevel(b.dataset.level);});
  el("skill-grid").addEventListener("click",e=>{const b=e.target.closest("[data-skill]");if(b)toggleSkill(b.dataset.skill);});
  el("custom-title").addEventListener("input",e=>{state.customTitle=e.target.value;});
  el("custom-start").addEventListener("click",startCustom);
  el("custom-back").addEventListener("click",showPick);
  el("topic-grid").addEventListener("click",e=>{const b=e.target.closest("[data-topic]");if(b)toggleTopic(b.dataset.topic);});
  el("start-interview").addEventListener("click",beginInterview);
  el("options").addEventListener("click",e=>{const b=e.target.closest("[data-option]");if(b)optionAnswer(Number(b.dataset.option));});
  el("lifelines").addEventListener("click",e=>{const b=e.target.closest("[data-lifeline]");if(b)useLifeline(b.dataset.lifeline);});
  el("question-actions").addEventListener("click",e=>{if(e.target.closest("[data-submit-order]"))submitOrder();if(e.target.closest("[data-reveal-open]"))revealOpen();const s=e.target.closest("[data-self]");if(s)selfScore(Number(s.dataset.self));});
  el("order-list").addEventListener("click",e=>{const b=e.target.closest("[data-order]");if(b)selectOrder(b.dataset.order);});
  el("order-list").addEventListener("dragstart",e=>{const b=e.target.closest("[data-order]");if(b)state.dragId=b.dataset.order;});
  el("order-list").addEventListener("dragover",e=>e.preventDefault());
  el("order-list").addEventListener("drop",e=>{e.preventDefault();const b=e.target.closest("[data-order]");if(b)dropOrder(b.dataset.order);});
  el("next-button").addEventListener("click",nextQuestion); el("replay-button").addEventListener("click",replay); el("roles-button").addEventListener("click",showPick); el("error-roles").addEventListener("click",showPick); el("error-retry").addEventListener("click",()=>state.job?.custom?startCustom():state.job?startJob(state.job.slug):loadJobs());
  window.addEventListener("keydown",e=>{if(state.screen==="interview"&&!state.locked&&["1","2","3","4"].includes(e.key)&&["mcq","red-flag"].includes(current().question.type))optionAnswer(Number(e.key)-1);});
  loadJobs();
})();
