#!/usr/bin/env python3
"""Check the content, then bundle it into content.js for the game to load.

content/ is where questions are authored and reviewed. content.js is generated
from it and is what the browser actually reads — a <script> tag works when the
page is opened straight off disk, whereas fetch() is blocked over file://.

Run this after adding a job title or writing new skill questions:
    python3 validate.py

Never hand-edit content.js. It is overwritten every run.
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).parent / "content"
STAGES = ["hr", "technical", "deepdive", "ask"]
LEVELS = ["junior", "mid", "senior"]
TYPES = {"mcq", "red-flag", "order", "open"}

errors, warnings = [], []

skills = {}
for f in sorted((ROOT / "skills").glob("*.json")):
    d = json.loads(f.read_text())
    if d["skill"] != f.stem:
        errors.append(f"{f.name}: skill id '{d['skill']}' does not match filename")
    skills[d["skill"]] = d
    for q in d["questions"]:
        where = f"{f.name}:{q['id']}"
        if q["type"] not in TYPES:
            errors.append(f"{where}: unknown type '{q['type']}'")
        if q["stage"] not in STAGES:
            errors.append(f"{where}: unknown stage '{q['stage']}'")
        if not q.get("levels") or any(l not in LEVELS for l in q["levels"]):
            errors.append(f"{where}: bad levels {q.get('levels')}")
        if not q.get("explanation"):
            errors.append(f"{where}: missing explanation")
        if q["type"] in ("mcq", "red-flag"):
            if len(q.get("options", [])) != 4:
                errors.append(f"{where}: needs exactly 4 options")
            if not 0 <= q.get("correct", -1) < 4:
                errors.append(f"{where}: correct out of range")
            if q.get("eliminate") == q.get("correct"):
                errors.append(f"{where}: eliminate points at the correct answer")
        if q["type"] == "order":
            ids = [i["id"] for i in q.get("items", [])]
            if sorted(ids) != sorted(q.get("correctOrder", [])):
                errors.append(f"{where}: correctOrder does not match items")
        if q["type"] == "open" and not q.get("keyPoints"):
            errors.append(f"{where}: open question needs keyPoints")

def pool(job, stage):
    """Every question this job could ask in this stage. behavioral is always in play."""
    ids = {s for t in job["topics"] for s in t["skills"]} | {"behavioral"}
    out = []
    for sid in sorted(ids):
        if sid not in skills:
            errors.append(f"{job['slug']}: references unknown skill '{sid}'")
            continue
        for q in skills[sid]["questions"]:
            if q["stage"] != stage:                         continue
            if job["level"] not in q["levels"]:             continue
            p = q.get("platform")
            if p and p != job["platform"]:                  continue
            out.append((sid, q))
    return out

jobs = [json.loads(f.read_text()) for f in sorted((ROOT / "job-titles").glob("*.json"))]
listed = {j["slug"] for j in jobs}
indexed = {j["slug"] for j in json.loads((ROOT / "index.json").read_text())["jobs"]}
if listed != indexed:
    errors.append(f"index.json out of sync: {listed ^ indexed}")

for job in jobs:
    if len(job["topics"]) != 6:
        errors.append(f"{job['slug']}: needs exactly 6 topics, has {len(job['topics'])}")
    print(f"\n{job['title']}  [{job['level']}/{job['platform']}]")
    for rnd in job["rounds"]:
        have = pool(job, rnd["id"]) + [("extra", q) for q in job["extra"]
                                       if q.get("stage") == rnd["id"]]
        need = rnd["count"]
        slack = len(have) - need
        flag = "FAIL" if slack < 0 else ("tight" if slack <= 1 else "ok")
        if slack < 0:
            errors.append(f"{job['slug']}/{rnd['id']}: needs {need}, only {len(have)} available")
        elif slack <= 1:
            warnings.append(f"{job['slug']}/{rnd['id']}: {len(have)} available for {need} — "
                            f"every play draws almost the same questions")
        print(f"  {rnd['name']:18s} need {need:2d}  have {len(have):2d}  {flag}")

print()
for w in warnings: print("warn:", w)
for e in errors:   print("ERROR:", e)
print(f"\n{sum(len(s['questions']) for s in skills.values())} questions "
      f"across {len(skills)} skills, {len(jobs)} job titles")

if errors:
    print("\ncontent.js NOT rebuilt — fix the errors above first.")
    sys.exit(1)

files = {"content/index.json": json.loads((ROOT / "index.json").read_text())}
for f in sorted((ROOT / "job-titles").glob("*.json")):
    files[f"content/job-titles/{f.name}"] = json.loads(f.read_text())
for f in sorted((ROOT / "skills").glob("*.json")):
    files[f"content/skills/{f.name}"] = json.loads(f.read_text())

bundle = pathlib.Path(__file__).parent / "content.js"
bundle.write_text(
    "// GENERATED by validate.py from content/ — do not edit by hand.\n"
    "// Bundled so the game works when index.html is opened straight off disk.\n"
    "window.CTI_CONTENT = "
    + json.dumps({"files": files}, indent=1, ensure_ascii=False)
    + ";\n")
print(f"content.js rebuilt — {len(files)} files, {bundle.stat().st_size // 1024} KB")
sys.exit(0)
